name: Web Newsletter - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - webform
config:
  strict: false
  import:
    webform: '*'
  actions:
    webform.settings:
      simpleConfigUpdate:
        libraries.excluded_libraries:
          - choices
          - jquery.chosen
          - codemirror
          - jquery.select2
          - tabby
          - popperjs
          - tippyjs
